note_app/urls.py
from django.urls import path
from .import views

app_name = 'note_app'

urlpatterns = [
  path('index/', views.index, name='index'),
  path('add/', views.add, name='add'),
  path('update/<int:pk>', views.update, name='update'),
  path('delete/<int:pk>', views.delete, name='delete'),
  path('detail/<int:pk>', views.detail, name='detail'),
]

note_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('note_app/', include('note_app.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
  path('user_list/', views.user_list, name='user_list'),
  path('index/', views.index, name='index'),
  path('register/', views.register, name='register'),
  path('user_login/', views.user_login, name='user_login'),
  path('user_logout/', views.user_logout, name='user_logout'),
  path('info/', views.info, name='info'),
]

note_app/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Create your models here.
class Note(models.Model):
  user_id = models.ForeignKey(
    User, on_delete=models.RESTRICT
  )
  title = models.CharField('タイトル',max_length=200)
  text = models.TextField('本文')
  category = models.CharField('分類',max_length=200)
  create_at = models.DateTimeField(default=timezone.now)
  update_at = models.DateTimeField(default=timezone.now)

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  website = models.URLField(blank=True)
  picture = models.FileField(upload_to='user/',blank=True)

  def __str__(self):

    return self.user.username

note_app/forms.py
from django import forms
from .models import Note
from user.models import User

class NoteCreateForm(forms.ModelForm):

  class Meta:
    model = Note
    fields = ['title','text','category','create_at','update_at','user_id']

user/forms.py
from django import forms
from django.contrib.auth.models import User
from user.models import Profile

class UserForm(forms.ModelForm):
  password = forms.CharField(label='パスワード',widget=forms.PasswordInput())
  class Meta():
    model = User
    fields = ('username', 'email', 'password')

class ProfileForm(forms.ModelForm):
  website = forms.URLField(label='ホームページ')
  picture = forms.FileField(label='写真')

  class Meta():
    model = Profile
    fields = ('website', 'picture')

class LoginForm(forms.Form):
    username = forms.CharField(label='名前', max_length=150)
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password !=confirm_password:
            raise forms.ValidationError('パスワードが一致しません')

note_app/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import NoteCreateForm
from .models import Note
from user.models import User

def index(request):
  context={
    'note_list':Note.objects.all(),
  }
  return render(request,'note_app/note_list.html',context)

def add(request):
  # 送信内容を基にフォームを作成し、POSTでなければ空のフォーム
  form = NoteCreateForm(request.POST or None)

  # method = POST、送信ボタン押下時、入力内容に問題なければ
  if request.method == 'POST':
    if form.is_valid():
        print("検証に成功しました。データを保存します")
        form.save()
        return redirect('note_app:index')
    else:
        print("検証に失敗したので、データを保存しません。検証に失敗した理由を次に表示します。")
        print(form.errors)


  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示 
  context = {
    'form':form
  }
  return render(request,'note_app/note_form.html',context)

def update(request,pk):
  note = get_object_or_404(Note,pk=pk)

  form = NoteCreateForm(request.POST or None,instance=note)

  if request.method == 'POST' and form.is_valid():
    form.save()
    return redirect('note_app:index')

  context={
    'form':form
  }
  return render(request,'note_app/note_form.html',context)

def delete(request,pk):
  note = get_object_or_404(Note,pk=pk)

  if request.method == 'POST':
    note.delete()
    return redirect('note_app:index')

  context={
    'note':note
  }
  return render(request,'note_app/note_confirm_delete.html',context)

def detail(request,pk):
  note = get_object_or_404(Note,pk=pk)

  context={
    'note':note
  }
  return render(request,'note_app/note_detail.html',context)

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user.forms import UserForm, ProfileForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def user_list(request):
  return render(request, 'user/user_list.html')

def index(request):
  return render(request, 'user/index.html')

def register(request):
  user_form = UserForm(request.POST or None)
  profile_form = ProfileForm(request.POST or None, request.FILES or None)
  if user_form.is_valid() and profile_form.is_valid():
    user = user_form.save()
    user.set_password(user.password)
    user.save() #ユーザ保存
    profile = profile_form.save(commit=False)
    profile.user = user
    profile.save()
  return render(request, 'user/registration.html', context={
    'user_form': user_form,
    'profile_form': profile_form,
  })

def user_login(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username')
        password = login_form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('user:index')
            else:
                return HttpResponse('アカウントがアクティブでないです')
        else:
            return HttpResponse('ユーザが存在しません')
    return render(request, 'user/login.html', context={
        'login_form': login_form
    })

@login_required
def user_logout(request):
    logout(request)
    return redirect('user:index')

@login_required
def info(request):
    return HttpResponse('ログインしています')

note_app/templates/note_app/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>NOTE</title>
  </head>
  <body>
    <div class="container">
    <nav class="nav">
      <a class="nav-link" href="{% url 'note_app:index' %}">一覧</a>
      <a class="nav-link" href="{% url 'note_app:add' %}">追加</a>
    </nav>
    {% block content %}
    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

note_app/templates/note_app/note_confirm_delete.html
{% extends 'note_app/base.html' %}

{% block content %}
<form action='' method=POST>
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{note.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{note.text}}</td>
    </tr>
    <tr>
      <th>分類</th>
      <td>{{note.category}}</td>
    </tr>
</table>
<p>こちらのデータを削除します。</p>
<button type='submit' class="btn btn-primary">削除</button>
{% csrf_token %}
</form>
{% endblock %}

note_app/templates/note_app/note_detail.html
{% extends 'note_app/base.html' %}

{% block content %}

<table class="table">
  <tr>
    <th>タイトル</th>
    <td>{{note.title}}</td>
  </tr>
  <tr>
    <th>本文</th>
    <td>{{note.text | linebreaksbr}}</td>
  </tr>
  <tr>
    <th>分類</th>
    <td>{{note.category}}</td>
  </tr>
  <tr>
    <th>作成日</th>
    <td>{{note.create_at}}</td>
  </tr>
  <tr>
    <th>更新日</th>
    <td>{{note.update_at}}</td>
  </tr>
</table>
{% endblock %}

note_app/templates/note_app/note_form.html
{% extends 'note_app/base.html' %}

{% block content %}
<form action='' method=POST>
  <table class="table">
    <tr>
      <th>ユーザー</th>
      <td>{{form.user_id}}</td>
    </tr>
    <tr>
      <th>タイトル</th>
      <td>{{form.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{form.text}}</td>
    </tr>
    <tr>
      <th>分類</th>
      <td>{{form.category}}</td>
    </tr>
    <tr>
      <th>作成日</th>
      <td>{{form.create_at}}</td>
    </tr>
    <tr>
      <th>更新日</th>
      <td>{{form.update_at}}</td>
    </tr>
</table>
<button type='submit' class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

note_app/templates/note_app/note_list.html
{% extends 'note_app/base.html' %}

{% block content %}
<h1>ノート一覧</h1>
<h2>こんにちは、{{user.username}}さん!!</h2>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>分類</th>
      <th>作成日</th>
      <th>更新日</th>
    </tr>
  </thead>
  <tbody>
    {% for note in note_list %}
    <tr>
      <td><a href="{% url 'note_app:detail' note.pk %}">{{note.title}}</a></td>
      <td>{{note.category}}</td>
      <td>{{note.create_at}}</td>
      <td>{{note.update_at}}</td>
      <td><a href="{% url 'note_app:update' note.pk %}">編集</a></td>
      <td><a href="{% url 'note_app:delete' note.pk %}">削除</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

user/templates/user/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>YOUR APP PLATFORM</title>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <a href="{% url 'user:index' %}">ホーム</a>
      <a href="{% url 'admin:index' %}">管理画面</a>
    {% if user.is_authenticated %}
      <a href="{% url 'user:user_logout' %}">ログアウト</a>
    {% else %}
      <a href="{% url 'user:register' %}">登録画面</a>
      <a href="{% url 'user:user_login' %}">ログイン</a>
    {% endif %}
      <a href="{% url 'user:info' %}">インフォメーション</a>
    </nav>

    <div>
      {% block content %}
      {% endblock %}
    </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/index.html
{% extends "user/base.html" %}
{% block content %}

<nav class="navbar sticky-top" style="background-color: #e3f2fd;">
  <h1>YOUR PLATFORM</h1>
</nav>
{% if user.is_authenticated %}
<h2>こんにちは、{{user.username}}さん!!</h2>
<div class="card">
  <div class="card-body">
    <h4 class="card-title">NOTE</h4>
    <p class="card-text">
      これはノートアプリです。
      勉強したことや気になることはここに残しましょう！
    </p>
    <a href="{% url 'note_app:index' %}" class="btn btn-primary">Go NOTE</a>
  </div>
</div>
{% else %}
<div class="alert alert-primary" role="alert">
    <strong>ログインまたは新規登録してください</strong> 
    <br>ログインまたは新規登録すれば各アプリケーションをご利用いただけます。</br>
</div>
{% endif %}
{% endblock %}

user/templates/user/login.html
{% extends "user/base.html" %}
{% block content %}
<h1>ログイン画面</h1>
<form method="POST">
{% csrf_token %}
{{ login_form.as_p }}
<input type="submit" value="ログイン">
</form>
{% endblock %}

user/templates/user/registration.html
{% extends "user/base.html" %}
{% block content %}
<h1>登録画面</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" value="登録">
</form>
{% endblock %}

user/templates/user/user_list.html
<h1>ユーザリスト</h1>
<a href="{% url 'note_app:index' %}">note list</a>